name: Build and deploy ASP.Net Core app to Azure Web App - easymenu-rm558883

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SOLUTION_PATH: EasyMenu-main/EasyMenu.sln
  API_PROJECT: EasyMenu-main/EasyMenu.Api.Admin/EasyMenu.Api.Admin.csproj
  PUBLISH_DIR: ${{ github.workspace }}/publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build (Release)
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ${{ env.API_PROJECT }} -c Release -o "${{ env.PUBLISH_DIR }}" --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: easymenu-publish
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: easymenu-publish
          path: ./app

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'easymenu-rm558883'
          slot-name: 'Production'
          package: ./app
